set -g @nova-segment-mode-colors "#8bd6b5 #0f1512"
set -g @nova-segment-whoami-colors "#8bd6b5 #0f1512"


set -g @nova-status-style-bg "#0f1512"
set -g @nova-status-style-fg "#8bd6b5"
set -g @nova-status-style-active-bg "#8bd6b5"
set -g @nova-status-style-active-fg "#0f1512"

set -g pane-border-style "fg=#0f1512"
set -g pane-active-border-style "fg=#8bd6b5"
