set -g default-terminal "tmux-256color"
setw -g mode-keys vi
set -ga terminal-overrides ",xterm-256color:RGB"

unbind %
bind v split-window -h
unbind '"'
bind s split-window -v

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuumnd'

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

set -g @themepack 'powerline/default/cyan'

run '~/.tmux/plugins/tpm/tpm'
