set -g default-terminal "tmux-256color"
setw -g mode-keys vi
set -ga terminal-overrides ",xterm-256color:RGB"

unbind %
bind v split-window -h
unbind '"'
bind s split-window -v

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuumnd'

set -g @plugin 'o0th/tmux-nova'

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#50fa7b #282a36"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#50fa7b #282a36"

source-file ~/.config/.tmux.colors.conf

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# set -g @themepack 'powerline/default/cyan'
run '~/.tmux/plugins/tpm/tpm'

source-file ~/.config/.tmux.colors.conf
