$applicationMenu = kitty -1 -o allow_remote_control=yes --class=applicationMenu --title=applicationMenu -o background_opacity=$overlay_window_opacity jiffy -x wl-copy -i 'OS.exec(["kitty", "@", "set-spacing", "margin=0"])' -r

bindd = $mainMod, Return, Launch application menu, exec, $applicationMenu

windowrule {
    name = application-menu
    match:title = ^(applicationMenu)$
    
    float = on
    center = 1
    size = 500 400
    animation = slide up
    border_size = 0
    rounding = 10
    pin = true
}
