#!/bin/bash

sudo mount -t cifs //${KODEKS_PC_IP}/rep /mnt/kodeks -o username=${KODEKS_PC_USERNAME},password=${KODEKS_PC_PASSWORD},uid=$(id -u),gid=$(id -g),domain=${KODEKS_PC_DOMAIN},vers=3.0,iocharset=utf8
