# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &

exec-once = bash /home/sherka/MyDirect/autorunScripts/bluetooth.sh
exec-once = waybar
exec-once = v2rayn
exec-once = telegram-desktop
exec-once = crow
exec-once = hyprpaper
