
############
### BASE ###
############

source = ~/.config/hypr/base/monitors.conf
source = ~/.config/hypr/base/programs.conf
source = ~/.config/hypr/base/autostart.conf
source = ~/.config/hypr/base/env.conf
source = ~/.config/hypr/base/permissions.conf
source = ~/.config/hypr/base/lookAndFeel.conf
source = ~/.config/hypr/base/input.conf
source = ~/.config/hypr/base/keybindings.conf
source = ~/.config/hypr/base/workspaces.conf


# OTHER
# source = ~/.config/hypr/other/jiffy.conf
source = ~/.config/hypr/other/fuzzel.conf
