[color]
background = 'default'
foreground = '#8bd6b5'

; gradient = 0
gradient = 1
gradient_color_1 = '#00513b'
gradient_color_2 = '#8bd6b5'
gradient_color_3 = '#a7f2d1'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#00513b'
horizontal_gradient_color_2 = '#8bd6b5'
horizontal_gradient_color_3 = '#a7f2d1'
horizontal_gradient_color_4 = '#8bd6b5'
horizontal_gradient_color_5 = '#00513b'
